name: deploy-container
# ? Due this action on pushes to master branch
on:
  push:
    branches:
      - master
    paths: # ? Only run this workflow on changes to container repo
      - "packages/container/**"

defaults:
  run:
    working-directory: packages/container # ? Set working directory to container

jobs:
  build:
    runs-on: ubuntu-latest # ? Github creates a ubunto VM

    steps:
      - uses: actions/checkout@v2 # ? Checkout the code from project run npm i and build webpack
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2 # ? Deploy to AWS
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest # ? Sync s3 bucket to the dist that was built by webpack at that wierd url
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ""
